### ISSUE TITLE
[setting] firebase hosting으로 CI/CD 구축

### ISSUE THREAD

**Issue by badaclockA** [byulhook/devchat#11]
### 📄 Description

PR 이후 배포 환경에서는 어떻게 나오는지는 바로바로 확인 할 수 있게함.

### ✅ Tasks

- [x] 파이어베이스 워크스페이스 등록하기
- [x] 파이어베이스 호스팅 세팅하기
- [x] 파이어베이스 호스팅 CI/CD workflow 세팅하기
