### ISSUE TITLE
[feature] 네비게이션바, react router dom 세팅하기

### ISSUE THREAD

**Issue by badaclockA** [byulhook/devchat#3]
### 📄 Description

React Router Dom을 설치하고 옆면 왼쪽에 위치한 네비게이션바를 만들 예정임.

### ✅ Tasks

- [x] React Router Dom 설치 
- [x] 네비게이션바 레이아웃 잡기
- [x] 수동 테스트 후 PR 올리기

**Comment by badaclockA** [comment]
레이아웃 영역을 좁힐까 고민중임.
![image](https://github.com/user-attachments/assets/8f001983-6720-4528-8800-7691db9b85e4)
![image](https://github.com/user-attachments/assets/a9d18e02-633e-4689-8a6a-f00216bdeab6)
