### ISSUE TITLE
[setting] github action으로 자동 PR 라벨링과 자동 PR 담당자 설정하기

### ISSUE THREAD

**Issue by badaclockA** [byulhook/devchat#5]
### 📄 Description

아래의 두 링크의 자료를 바탕으로 자동 라벨링과 자동 담당자를 설정하는 workflow 세팅하기
- https://github.com/marketplace/actions/auto-assign-action
- https://github.com/kentaro-m/auto-assign-action

+ 자동 이슈 라벨링도 할 예정
- https://github.com/marketplace/actions/assign-me-action

### ✅ Tasks

- [x] 자동 라벨링 세팅하기
- [x] 자동 담당자 설정 세팅하기
- [x] 프로젝트에 PR올려서 테스트하고 확인해보기
